### ISSUE TITLE
雷电模拟器

### ISSUE THREAD

**Issue by jay8520** [aicezam/SmartOnmyoji#11]
运行异常， 小白不知道怎么解决 大大帮帮忙
![无标题](https://user-images.githubusercontent.com/105167511/167306595-04b4db93-fb88-4aee-84a5-3364deae259f.png)

**Comment by aicezam** [comment]
今天下午刚好发现这个问题，兼容雷电模拟器那段代码少写了个return，现在已经更新了~
https://github.com/aicezam/SmartOnmyoji/releases

**Comment by jay8520** [comment]
![无标题](https://user-images.githubusercontent.com/105167511/167313066-61f2a725-de54-4725-8380-c3639bab54c7.png)
可以开启，也匹配成功了，但是不会点只是显示匹配成功。 我是弄错了什么了吗

**Comment by aicezam** [comment]
那个窗口标题只输雷电模拟器，去掉-1试试

**Comment by jay8520** [comment]
可以了，还有一个问题就是只能开兼容，后台用不了。

**Comment by aicezam** [comment]
![雷电模拟器匹配点击成功](https://user-images.githubusercontent.com/39365915/167368307-93700f77-d671-4790-ad83-4f3e5b454624.gif)
我改了一点点东西，试了下，可以后台的，你注意下那个运行日志里面输出的窗口标题是不是 “窗口名称: [ TheRender ]”

**Comment by aicezam** [comment]
用最新的试试https://github.com/aicezam/SmartOnmyoji/releases

**Comment by jay8520** [comment]
大佬我试了一下 单开是可以后台 双开就只能兼容

**Comment by aicezam** [comment]
暂时不知道为啥了，以后有空研究下
