### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by zs06005507** [aicezam/SmartOnmyoji#12]
**前置：**
用于挖土，使用桌面客户端，单刷。

**描述**
使用了几天，发现一个问题，就是 在挖土结算页面，会偶尔点到 `概率up` ，使页面弹出 `概率up` 介绍信息，页面整体变暗，特征图像被遮挡，程序无法进行下一步，建议加入相关特征图像以排查该情况。

**相关设置：**
点击坐标偏移：43 像素

建议补全该特征以解决此问题。

还有就是暂停两分钟时，希望出一个提示音的选项，让用户这段时间内手动操作或者进行其他操作以混淆行为。

**Comment by zs06005507** [comment]
感谢大佬第一时间回复！

是这个概率up。
![2121](https://user-images.githubusercontent.com/53304555/167373524-797c5f5a-7423-4442-b8ff-3910cb900353.JPG)

该问题在窗口宽度小于800(非具体)得以复现。

**Comment by aicezam** [comment]
害，就是那个截图的问题，御魂加成都快挨着结算的那个结果了，特征图片用的这几个，你可以重新截图截高点，替换掉文件夹里的图片就行了，就不会随机那么离谱到御魂加成上面了~
![image](https://user-images.githubusercontent.com/39365915/167375264-ab940dc8-2d16-41c6-8a98-b905fe916aa1.png)

**Comment by aicezam** [comment]
或者改下随机范围，20-30之间也不会飘那么远，这个范围指的是半径，实际随机范围是 -30 至 +30 之间

**Comment by zs06005507** [comment]
> 害，就是那个截图的问题，御魂加成都快挨着结算的那个结果了，特征图片用的这几个，你可以重新截图截高点，替换掉文件夹里的图片就行了，就不会随机那么离谱到御魂加成上面了~ ![image](https://user-images.githubusercontent.com/39365915/167375264-ab940dc8-2d16-41c6-8a98-b905fe916aa1.png)

好的，谢谢大佬~
我尝试一下

**Comment by zs06005507** [comment]
> 加提示音这个需求，已经实现了，可以下载最新包体验：https://github.com/aicezam/SmartOnmyoji/releases

赞美大佬~
