### ISSUE TITLE
iOS版本 闪电模拟器和mumu模拟器都不能使用

### ISSUE THREAD

**Issue by Juveline2000** [aicezam/SmartOnmyoji#15]
iOS版本 闪电模拟器和mumu模拟器都不能使用，详情界面能截图，但是不能点击事件

**Comment by aicezam** [comment]
是在windows系统运行脚本的吗？可以试试兼容模式能不能点起啊？

**Comment by Juveline2000** [comment]
> 是在windows系统运行脚本的吗？可以试试兼容模式能不能点起啊？

我试一下

**Comment by Juveline2000** [comment]
![1](https://user-images.githubusercontent.com/38997906/172629870-d9e8b1e3-22fc-4f85-896b-dc815d842afd.png)
iOS版本还是不行 我开启调试是可以截图和识别的 ，就是不能点击，安卓试了是可以的

**Comment by Juveline2000** [comment]
![ITCMTT6SWJAR8M~ Q830F$L](https://user-images.githubusercontent.com/38997906/172630352-dd7d0f90-f8f7-4553-9dc7-20f41601ba15.png)

**Comment by Juveline2000** [comment]
兼容模式错误
![Q1Y(J8YEMSC%6MPA S QGW8](https://user-images.githubusercontent.com/38997906/172631238-72b50f70-7fe6-47ee-a694-14a31eebe308.png)

**Comment by aicezam** [comment]
iOS版本是啥意思，看了下你截图，应该是没识别到MuMu模拟器，改天我尝试修复下问题，主要是我也没遇到过，我是一直是安卓手机
