### ISSUE TITLE
御魂只能刷组队的吗

### ISSUE THREAD

**Issue by Levi233** [aicezam/SmartOnmyoji#17]
![image](https://user-images.githubusercontent.com/21984877/175796230-4c75856f-ed1b-41dc-a36f-578517561020.png)
我匹配挑战，这个页面每次都是点组队

**Comment by Levi233** [comment]
![image](https://user-images.githubusercontent.com/21984877/175796407-a582da24-eea1-4553-8769-2703cf1a0aff.png)
都成功，就是点击的是组队

**Comment by aicezam** [comment]
![QQ图片20220626113124](https://user-images.githubusercontent.com/39365915/175798271-5c283983-b267-4d9a-9950-60fae4d520d2.png)
windows个性化设置，这里改成100%试试，应该是这个分辨率缩放的问题

**Comment by Levi233** [comment]
没用，我这个也试了，重新截图放进去，也还是点组队，不点挑战

**Comment by aicezam** [comment]
能截图看下你缩放的设置吗？还有那个显示分辨率，你截图上面，很明细是被系统缩放了显示大小的，正常是我截图这种显示，然后导致坐标计算的时候，因为分辨率尺寸的原因，点击坐标计算不准确，虽然能匹配但就是点的位置不一样，不同电脑的分辨率不一样，也没得啥好的方法兼容，最好是显示分辨率改成屏幕的实际分辨率，缩放就用100%
![image](https://user-images.githubusercontent.com/39365915/175800039-2796621f-0ce0-4804-99b5-dd7129ef67ab.png)

**Comment by Levi233** [comment]
![image](https://user-images.githubusercontent.com/21984877/175800172-e58d433d-775a-4206-b4da-a3b9650445ed.png)
![image](https://user-images.githubusercontent.com/21984877/175800178-db4563bb-c83f-4e44-9148-9739a47e2415.png)
我调了100%是一样的，还是点组队

**Comment by aicezam** [comment]
你显示分辨率还能调成别的吗？最大就是1920*1080么？

**Comment by Levi233** [comment]
![image](https://user-images.githubusercontent.com/21984877/175800253-a0fce803-aee6-42d4-9bc2-aab883620493.png)
是的，我笔记本最大1920*1080

**Comment by aicezam** [comment]
啊。那我真没啥办法了，对了，正常模式和兼容模式的坐标计算方法不一样，你试试兼容模式是不是也是匹配的组队？

**Comment by Levi233** [comment]
兼容模式偏离的更离谱，点的中间的蛇

**Comment by aicezam** [comment]
那绝对是分辨率的问题，我没遇到过你这种情况，没办法了，你会不会python，可以尝试自己调试一下，以下几段代码是跟坐标计算相关的
![image](https://user-images.githubusercontent.com/39365915/175800739-bca725b9-657b-4736-8d66-39f323ed4a0d.png)
![QQ图片20220626133043](https://user-images.githubusercontent.com/39365915/175800842-77e83e76-d67f-42b7-98ae-6dfae07ff873.png)

**Comment by Levi233** [comment]
可惜不会，不过还是谢谢回答

**Comment by aicezam** [comment]
😂 可惜没帮到你~
