### ISSUE TITLE
开启显示winerror 225

### ISSUE THREAD

**Issue by keriou1** [aicezam/SmartOnmyoji#18]
![QQ截图20220627161915](https://user-images.githubusercontent.com/108262060/175894037-80954e79-4d23-4be4-98eb-36cbe602a1a3.png)

**Comment by aicezam** [comment]
好像是被360当成木马查杀了，你检查一下主目录里面的 /modules/adb.exe 和另外2个dll文件还在不在，你可以重新找个abd程序放在这个目录里面

**Comment by keriou1** [comment]
看了下文件还在，但是重新下载启动还是这样。

**Comment by aicezam** [comment]
雷电模拟器或者桌面版不会调用adb程序，如果用不了桌面版你可以试试雷电模拟器
