### ISSUE TITLE
开3个模拟器，只有一个模拟器能顺利运行

### ISSUE THREAD

**Issue by wukuangcs** [aicezam/SmartOnmyoji#21]
3开蓝mumu，自己截图了，匹配也能顺利匹配上，但是只有第一个窗口会自动点击，另外2个窗口不会点击。
请问这个问题怎么解决啊？
![QQ图片20220908114359](https://user-images.githubusercontent.com/103926218/189029495-b97e47e8-6088-4d4b-9a17-b24638b6e8dc.png)

**Comment by aicezam** [comment]
这里是模拟器多开原理的问题，模拟器多开之后，每个窗口对应的端口号不一样，但是脚本获取不到端口号，所以另外两个窗口匹配不上，MUMU模拟器本身不支持win窗口点击（所以脚本采用了adb去连接），建议把MUMU换成雷电模拟器，或者桌面版，这俩支持比较好

**Comment by wukuangcs** [comment]
好的，我试用一下雷电模拟器
