### ISSUE TITLE
待优化内容 ~

### ISSUE THREAD

**Issue by aicezam** [aicezam/SmartOnmyoji#24]
- [x] 模拟真实点击的算法，~~需要根据截图的范围大小确定点击的随机位置（另外增加限制，每X次点击触发N次）~~ 改为从正态分布的数组中抽取，而不是平均分布中取样
- [x] 随机等待的触发机制优化，（增加限制，每X次匹配成功最多触发Y次等待）
- [ ] 代码简化，每次匹配前的初始化部分代码，有点过于混乱（当时为了考虑各种情况，部分代码可以封装为函数调用）
- [ ] 对模拟器多开兼容（先找找能不能获取到端口号，找不到就只有配置文件手动加了）
- [ ] 优化脚本的等待时间，限制10分钟不超过N次点击，每次匹配间隔设置上下限时间
- [ ] 匹配速度优化，去除部分没有必要的延迟，尝试对截图预处理看看能否提升匹配速度（分辨率过大的提前压缩，转灰度/二值化处理）
- [ ] 安卓端移植，参考 https://www.zhihu.com/column/c_1500045392640786432 、https://github.com/superzhangjh/AutoTouch

**Comment by runhey** [comment]
提点自己的想法
+ 希望有一种运行模式，是更加智能化的运行，既可以按照一定的图片流顺序进行点击（当然这个不一定是非得这次点击是这张图片，下次必须是另一张图片），希望有一定的优先级顺序
+ 客户端的多样性，用户脚本用途的多样性，使得对“目标名称”的选择需求变多，而当下只有写死的六种模式显得太少，希望可以有可变的选择
+ 有一个从我接触源码配置设置的不明所以，云里雾里的使用ini作为配置文件，由于其语法的简单使得后期更新的时候只能进行无脑堆叠，使得整个程序后期臃肿无章法，可以重写为json或者yaml toml
+ 当前界面对用户暴露过多设置，感受出随着软件的更新没有一定的组织结构，过于杂乱，可以选择在界面处写一个通用的可以随着配置文件选项增加而增加的 用户接口，一是可以优化界面，二是防呆处理，三是可以为了以后更新兼容
+ 还是关于用户界面的，站在21世纪的重度互联网用户来说，这个上个世纪的风格属实接受不了，如果我来选我选qml，
还可以只留下右边的Log输出，设置以另一个dialog弹窗来设置
![image](https://user-images.githubusercontent.com/74492025/193619528-d519fbf0-90c7-4dd1-9e88-b7135be9ba83.png)

+ 还有一个能当我没说的选用python实在是...太太太吃cpu了，运行时连桌面版这两个程序，我笔记本cpu直接飙升到百分之六七十，脚本吃掉了十多二十多，......有一说一如果技术选型我来选我还是会选python

**Comment by aicezam** [comment]
> 提点自己的想法
> 
> * 希望有一种运行模式，是更加智能化的运行，既可以按照一定的图片流顺序进行点击（当然这个不一定是非得这次点击是这张图片，下次必须是另一张图片），希望有一定的优先级顺序
> * 客户端的多样性，用户脚本用途的多样性，使得对“目标名称”的选择需求变多，而当下只有写死的六种模式显得太少，希望可以有可变的选择
> * 有一个从我接触源码配置设置的不明所以，云里雾里的使用ini作为配置文件，由于其语法的简单使得后期更新的时候只能进行无脑堆叠，使得整个程序后期臃肿无章法，可以重写为json或者yaml toml
> * 当前界面对用户暴露过多设置，感受出随着软件的更新没有一定的组织结构，过于杂乱，可以选择在界面处写一个通用的可以随着配置文件选项增加而增加的 用户接口，一是可以优化界面，二是防呆处理，三是可以为了以后更新兼容
> * 还是关于用户界面的，站在21世纪的重度互联网用户来说，这个上个世纪的风格属实接受不了，如果我来选我选qml，
>   还可以只留下右边的Log输出，设置以另一个dialog弹窗来设置
>   ![image](https://user-images.githubusercontent.com/74492025/193619528-d519fbf0-90c7-4dd1-9e88-b7135be9ba83.png)
> * 还有一个能当我没说的选用python实在是...太太太吃cpu了，运行时连桌面版这两个程序，我笔记本cpu直接飙升到百分之六七十，脚本吃掉了十多二十多，......有一说一如果技术选型我来选我还是会选python

大佬说的都有道理，也是我有思考过的方向，只是超出了我的能力范畴，目前对于程序结构也没有深入的学习，很多程序思想也只是了解个皮毛，很多东西都是现查的，之所以选python也是因为简单，目前这个脚本有很多可以优化的地方，偶尔更新一下也是怕自己忘了这个唯一一门程序语言，后面的优化也主要是算法层面上的，提升匹配的效率和完善混淆点击的算法（因为朋友的黑号又被封了，不是黑号的没有被封，说明防封的算法还是有点问题）

**Comment by Lin-plax** [comment]
能否对脚本在安卓端的使用增加一些说明？感谢
