### ISSUE TITLE
雷电模拟器只能使用兼容模式

### ISSUE THREAD

**Issue by Ryankira** [aicezam/SmartOnmyoji#25]
正在截图…
截图成功！
正在匹配…
匹配成功! 
匹配到第 [ 3 ] 张图片: [ 1 ]
坐标位置: [ 1002 , 548 ] 
点击坐标: [ 1021 , 526 ] 
正常模式下他的点击似乎没有反应（无遮挡且调试模式看窗口正常）
另外问一下双开组队刷御魂要怎样设置

**Comment by aicezam** [comment]
> 正在截图… 截图成功！ 正在匹配… 匹配成功! 匹配到第 [ 3 ] 张图片: [ 1 ] 坐标位置: [ 1002 , 548 ] 点击坐标: [ 1021 , 526 ] 正常模式下他的点击似乎没有反应（无遮挡且调试模式看窗口正常） 另外问一下双开组队刷御魂要怎样设置

- 模拟器不支持后台双开，只能兼容模式下双开，组队刷御魂需要先组队，锁定阵容，刷一次，再开脚本
- 正常模式下点击没有反应，这个问题我抽空再看看，能否截图看下你模拟器窗口的名称？雷电模拟器名称是写死在代码里面的，不确定是不是因为名称没匹配上

**Comment by Ryankira** [comment]
名称是匹配上的，我一开始以为是中文名称的原因，后来改成英文加数字一样可以匹配上，但是点击一样没反应。雷电4.0.81设定的是手机版720*1280

**Comment by xiaorui77** [comment]
我这个也不能后台运行,  雷电版本: 5.0.36
如图, 我debug了一下,  截图出来的图片是黑的
<img width="927" alt="Snipaste_2022-10-13_16-41-51" src="https://user-images.githubusercontent.com/33676932/195547692-6b2cca6b-05cd-4dbb-8f87-395444596a67.png">

**Comment by aicezam** [comment]
不知道更新了什么东西，可能模拟器的句柄结构变了，之前的雷电模拟器的TheRender可以支持后台点击，不晓得现在是不是改了什么东西，可能就跟MUMU模拟器一样，死活找不到怎么后台截图和点击
![image](https://user-images.githubusercontent.com/39365915/195551876-9f74f7a7-6e47-4955-b880-8b9ea93613f0.png)

**Comment by Ryankira** [comment]
请问那使用模拟器怎样调用abd模式呢，是不是就可以解决后台刷图和兼容性问题了

**Comment by aicezam** [comment]
如果改代码，试试把有“雷电”的字符，改成“NONE”或者其他什么字符，应该就不会特殊处理雷电模拟器了，或者匹配目标选择使用"Android"模式试试，如果知道IP和端口号，可以在配置文件中改下wifi那个配置，设置成模拟器的IP和端口号，话说好久没调试模拟器了，我忘了代码逻辑了都 😂
