### ISSUE TITLE
请问每次匹配间隔是固定的吗？可以设置两个时间段的范围内随机数吗？比如2-2.5s防检测

### ISSUE THREAD

**Issue by dingxiansen1** [aicezam/SmartOnmyoji#26]

**Comment by aicezam** [comment]
有做随机延迟，会随机增加或减少（-0.5 - 0.5）秒
另外不是每次匹配都会点击游戏，而是匹配成功之后才会点击游戏
![image](https://user-images.githubusercontent.com/39365915/193015410-558d0239-78b1-4af8-b8f0-6bdeb53fdb12.png)

**Comment by dingxiansen1** [comment]
感谢大佬回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aicezam/SmartOnmyoji"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 晚上7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aicezam/SmartOnmyoji] 请问每次匹配间隔是固定的吗？可以设置两个时间段的范围内随机数吗？比如2-2.5s防检测 (Issue #26)





 
有做随机延迟，会随机增加或减少（-0.5 - 0.5）秒
 另外不是每次匹配都会点击游戏，而是匹配成功之后才会点击游戏
