### ISSUE TITLE
关于匹配到五次图片就停止脚本的操作

### ISSUE THREAD

**Issue by vegetpig** [aicezam/SmartOnmyoji#27]
你好，我想请问一下最新版本v0.28，如何设置匹配到五次图片不停止脚本呢？如果没有这个功能的话，麻烦能否在下个版本中添加一下呢，谢谢！

**Comment by aicezam** [comment]
@vegetpig 已更新，可在最新版的配置文件中修改，默认开启这个功能，可改为False关闭
