### ISSUE TITLE
是否考虑增加自动检测配置文件

### ISSUE THREAD

**Issue by chen8945** [aicezam/SmartOnmyoji#28]
1. 举个例子，把原来的 `config.ini` 文件改名为 `config.example.ini`，然后在程序启动时检测是否存在 `config.ini`，如果不存在，则将默认配置复制一份进行重命名，如果存在，则跳过。这样在更新的时候就不会覆盖掉原先已经改好的设置
2. 另外就是可否在右上角添加一个按钮，让程序图标能够缩小到右下角托盘里面

**Comment by aicezam** [comment]
好麻烦啊 😰 有空了看看怎么弄吧

**Comment by chen8945** [comment]
> 好麻烦啊 😰 有空了看看怎么弄吧

大佬加油，有空了再搞
