### ISSUE TITLE
后台点击不支持安卓模拟器

### ISSUE THREAD

**Issue by Tiramisu20** [aicezam/SmartOnmyoji#3]
没下到阴阳师的PC版，现在只有模拟器版。然后后台点击在模拟器环境下（MuMu模拟器）是没有反应的。
测试了其他程序（Chrome）是可以后台点击的。

**Comment by aicezam** [comment]
> 没下到阴阳师的PC版，现在只有模拟器版。然后后台点击在模拟器环境下（MuMu模拟器）是没有反应的。 测试了其他程序（Chrome）是可以后台点击的。

确实不支持安卓模拟器，如果已经使用模拟器，相当于你电脑连了一台手机，可用用adb方式连接试试（不过需要重新截图啥的），没测试过，但是应该可行

**Comment by aicezam** [comment]
![image](https://user-images.githubusercontent.com/39365915/154682278-83d4fef5-2463-4dba-ba9c-514cf03d1d70.png)

**Comment by aicezam** [comment]
> 感谢指路！我今天研究了一天，查了些资料，试了一下，发现雷电模拟器的一个子窗体可以正常接收后台点击事件。MuMu模拟器就比较奇葩怎么都不行。 我最近在研究 Python 做 EVE手游 的脚本，如果方便的话不知道能不能加一下大佬您的联系方式？

都用安卓模拟器了，其实没必要用win32的库了，adb功能很全很强大的，不过之前了解过，不同模拟器用的端口好像不一样，另外我也是才学的，只会一点点python，不是大佬哈，联系方式就不用了

**Comment by aicezam** [comment]
加了新的截图和点击方法，只是这种方法不能后台，但是可以兼容其他窗体程序了
