### ISSUE TITLE
封号

### ISSUE THREAD

**Issue by TIANYAMINGYUEJIAN** [aicezam/SmartOnmyoji#31]
大佬我被封了呢，您有被封过吗

**Comment by aicezam** [comment]
你是哪个版本？是怎么用的可以描述一下吗？如果是0.3以上的，有日志的话可以上传一下不？

**Comment by TIANYAMINGYUEJIAN** [comment]
我最近没怎么用樱饼，因为御魂上限了，一直没有清，0.17

**Comment by aicezam** [comment]
版本太老了，新版加了点击模型，可以看下readme的描述，旧版本超过一定次数就容易被封，因为点击的位置太固定，会形成一个规则的形状，他们人工核实的时候一下就看出问题了

**Comment by TIANYAMINGYUEJIAN** [comment]
不过大佬，感谢您的项目，让我坚持了一年又，我不太想玩这个游戏了。用脚都觉得心累的那种

**Comment by aicezam** [comment]
啊 好叭

**Comment by TIANYAMINGYUEJIAN** [comment]
大佬您可以方便给个联系方式吗，当交个朋友了，真的很谢谢您

**Comment by aicezam** [comment]
不用了吧，我社恐

**Comment by TIANYAMINGYUEJIAN** [comment]
是这样的，我最近这一年因为事情很多，一直被这些压的喘不过气来，年初在github上看到您的项目真的帮了我很多，我自己写的脚本效率太低，您看真的，如果方便的话，

**Comment by TIANYAMINGYUEJIAN** [comment]
好吧對不起打擾了，我真的很感謝您的項目，幫我分擔了一點。

**Comment by aicezam** [comment]
没有，我只是社恐，人生多彩，加油吧！
