### ISSUE TITLE
关于正常模式截图问题

### ISSUE THREAD

**Issue by Milchsra** [aicezam/SmartOnmyoji#32]
作者您好
开正常模式进行调试会发现，截图是黑屏，或者只有坐上一部分，尝试修改缩放比例未果，请问这是为什么呢。开兼容模式可以正常截图。

**Comment by aicezam** [comment]
看下截图效果呢？看你描述应该是分辨率的问题

**Comment by Milchsra** [comment]
![QQ截图20221028201501](https://user-images.githubusercontent.com/116878443/198585388-30d2b968-9303-465d-96ae-f6f9d256bb4b.jpg)
会出现这种情况。截图整体往左上角偏移。游戏的分辨率是默认的，显示器为2k，用笔记本1080p尝试结果一样
或者干脆截下来的是黑屏
![QQ截图20221028200233](https://user-images.githubusercontent.com/116878443/198585507-255a8449-5e4a-4b19-8f4e-797c56e6fe76.jpg)

**Comment by aicezam** [comment]
就是分辨率的问题，你改小点呢，试试改成 1 ，主要还是要跟系统的分辨率保持一致

**Comment by Milchsra** [comment]
之前尝试过了，谢谢，我再多调一下，感谢作者
