### ISSUE TITLE
请问为什么匹配进度到81%就脚本就自动停止了？

### ISSUE THREAD

**Issue by Lin-plax** [aicezam/SmartOnmyoji#33]
![yys_bug](https://user-images.githubusercontent.com/66245091/198827077-c40e0d32-5e92-45cc-9b54-f2862cf7b920.jpg)
如图所示，每次运行到81%的时候程序就自动停止了

**Comment by aicezam** [comment]
emmmmmm 奇奇怪怪的bug，我回头试试

**Comment by aicezam** [comment]
已修复~

**Comment by Lin-plax** [comment]
> 已修复~

非常感谢~
