### ISSUE TITLE
考虑支持3人队伍吗？

### ISSUE THREAD

**Issue by YoungDJean** [aicezam/SmartOnmyoji#34]
开了3个号组队魂土，但是识图到就会点击，队伍两个人就会开始打；期望有个开关的配置可以判断一下组满再开始

**Comment by aicezam** [comment]
如果要改的话，整个脚本的逻辑都要重构，如果要3人组队，可以试试这样：
把队长的窗口放在最后匹配（先获取队员的窗口编号再获取队长的），然后间隔时间设长一点，这样就会在前两个队友完成匹配点击后，队长最后再开始匹配

**Comment by YoungDJean** [comment]
> 如果要改的话，整个脚本的逻辑都要重构，如果要3人组队，可以试试这样： 把队长的窗口放在最后匹配（先获取队员的窗口编号再获取队长的），然后间隔时间设长一点，这样就会在前两个队友完成匹配点击后，队长最后再开始匹配

好的。我试一下，谢谢
