### ISSUE TITLE
0.34桌面版能匹配成功却不会自动点击

### ISSUE THREAD

**Issue by Chash1997** [aicezam/SmartOnmyoji#38]
作者能否修复一下呢

**Comment by aicezam** [comment]
之前版本可以正常点击吗？还是说第一次用？

**Comment by aicezam** [comment]
我桌面版运行很正常啊，有截图或者录屏吗我看看？

**Comment by Chash1997** [comment]
在刷999的那段时间我用来刷御魂还是可以的，现在不知道为啥不行了

**Comment by Chash1997** [comment]
![1](https://user-images.githubusercontent.com/117435604/199965766-54ea6472-b400-4e08-99b5-48c5ce34a30d.png)

**Comment by Chash1997** [comment]
就是匹配成功，但是就是不点击挑战。

**Comment by aicezam** [comment]
用正常模式会点击吗？

**Comment by aicezam** [comment]
用兼容模式可以点击吗？

**Comment by Chash1997** [comment]
不可以，都试过了。是我缩放的问题吗？我是笔记本所以是125%。以前的话是只能用特征点。而且界面一直都显示不全面

**Comment by Lin-plax** [comment]
没缩放100%

**Comment by Chash1997** [comment]
确实是缩放的问题。作者有空能适配一下125%的嘛？笔记本100字太小了T T

**Comment by aicezam** [comment]
> 不可以，都试过了。是我缩放的问题吗？我是笔记本所以是125%。以前的话是只能用特征点。而且界面一直都显示不全面

缩放问题可以改配置文件
![image](https://user-images.githubusercontent.com/39365915/199977856-df138543-cbbd-4d91-b0c0-c4983f81282b.png)

**Comment by aicezam** [comment]
你改成1.25就适配你的电脑了

**Comment by Chash1997** [comment]
但是改成1.25后就匹配失败了
![2](https://user-images.githubusercontent.com/117435604/199993207-36722bba-dfd6-4766-b35c-01facee9fdab.png)

**Comment by Chash1997** [comment]
噢原来是这样的，谢谢

**Comment by Chash1997** [comment]
另外大佬，以后是否会加标记和次数的功能呢

**Comment by aicezam** [comment]
> 另外大佬，以后是否会加标记和次数的功能呢

有计划，但是没想好怎么做
