### ISSUE TITLE
探索副本

### ISSUE THREAD

**Issue by hanwenhao369** [aicezam/SmartOnmyoji#39]
探索是只能等怪走过来才能匹配到吗？还是得自己手动点击移动

**Comment by aicezam** [comment]
探索默认只支持第28章（因为只截取了28章的地图），如果要打其他章节，或者窗口尺寸更新啥的，还需要重新截图，目标图片里面，需要把地图的一部分截图进去，当没有战斗图标的时候，就会匹配地图位置，可以自动点过去
