### ISSUE TITLE
鼠标点击 多窗口和模拟器问题

### ISSUE THREAD

**Issue by lisadaddy** [aicezam/SmartOnmyoji#4]
您好，我想请问下，如果多个游戏窗口的话，鼠标点击事件可以并发操作吗？ 另外这个切图和坐标工具这一套是什么实现的

谢谢了。一些问题麻烦指导。

**Comment by aicezam** [comment]
> 您好，我想请问下，如果多个游戏窗口的话，鼠标点击事件可以并发操作吗？ 
你的问题应该不只是点击事件吧，还有截图和匹配能否并发，有两种方式可以实现并发操作，一种是改代码，把多个窗口的句柄存在数组里面，然后针对这组句柄进行循环截图和点击，也可以改成线程的方式，每个线程一个句柄（具体怎么操作还没研究，后面重构UI的时候可以考虑加上这个功能），另一种方法要简单些，就是多开几个这个辅助脚本（每个要点击的游戏窗口开一个对应的脚本，没法一个脚本对应多个窗体）

> 另外这个切图和坐标工具这一套是什么实现的
不清楚你什么意思？并没有使用到任何切图和坐标工具，如果是代码里面截图方法的话，后台截图用的cv2实现，前台截图用的PIL，坐标是用pywin32获取的窗体坐标和cv2的匹配到的坐标，相加减计算出来的

**Comment by aicezam** [comment]
> 您好，我想请问下，如果多个游戏窗口的话，鼠标点击事件可以并发操作吗？

你的问题应该不只是点击事件吧，还有截图和匹配能否并发，有两种方式可以实现并发操作，一种是改代码，把多个窗口的句柄存在数组里面，然后针对这组句柄进行循环截图和点击，也可以改成线程的方式，每个线程一个句柄（具体怎么操作还没研究，后面重构UI的时候可以考虑加上这个功能），另一种方法要简单些，就是多开几个这个辅助脚本（每个要点击的游戏窗口开一个对应的脚本，没法一个脚本对应多个窗体）

> 另外这个切图和坐标工具这一套是什么实现的

不清楚你什么意思？并没有使用到任何切图和坐标工具，如果是代码里面截图方法的话，后台截图用的cv2实现，前台截图用的PIL，坐标是用pywin32获取的窗体坐标和cv2的匹配到的坐标，相加减计算出来的

**Comment by lisadaddy** [comment]
了解了，非常详尽了。我也是刚学习，还在摸索中。感谢感谢

**Comment by lisadaddy** [comment]
能加个微信吗 我在上海工作  yazhen457

**Comment by aicezam** [comment]
额，不必了吧，而且你这微信号也不存在啊

**Comment by Colibrow** [comment]
尝试起了多个进程发现鼠标位置没法在多个窗口来回动(用的Pyinstaller打出来的exe)

**Comment by aicezam** [comment]
> 尝试起了多个进程发现鼠标位置没法在多个窗口来回动(用的Pyinstaller打出来的exe)

我自己测试的时候，是俩不同的窗口，突然想起来，如果窗口名称一样，就会冲突，有个窗口必定找不到，所以会失败，改天我加个兼容多开的功能~

**Comment by Colibrow** [comment]
是的，我把window的title改成了handle，本地是可以了，然后目前我设置的匹配间隔是2s，这个应该到1s也没啥问题吧

**Comment by aicezam** [comment]
肯定没问题啊，只要不是一直点同一个坐标点就不会有问题

**Comment by aicezam** [comment]
已更新支持一个脚本同时支持匹配多个窗口的功能~ @Colibrow

**Comment by Colibrow** [comment]
> 已更新支持一个脚本同时支持匹配多个窗口的功能~ @Colibrow

优秀，不过我刷不了了，四个号被鬼使黑了。

**Comment by aicezam** [comment]
emmmmm，太奔放了吧，我还没被鬼使黑找过
