### ISSUE TITLE
关于双开的问题

### ISSUE THREAD

**Issue by Lin-plax** [aicezam/SmartOnmyoji#40]
请问双开的时候，截屏、点击顺序是什么？
我发现，打开多开以后，有时候司机点的慢，有时候又快。
司机和打手很大概率不会同时截屏点击。
请问是有什么设置吗？还是说是我电脑配置不够的问题？

**Comment by aicezam** [comment]
基于安全考虑，每次点击匹配都可能触发一次额外点击，会随机在非目标位置点击一次，所以偶尔会导致点不上，这个概率可以在配置文件里面调整，默认是100次触发15次
