### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by Color-More** [aicezam/SmartOnmyoji#41]
寮突破能否安排一下

**Comment by aicezam** [comment]
可以，但没必要，寮突打六次就要冷却半小时。。。。

**Comment by Color-More** [comment]
> 可以，但没必要，寮突打六次就要冷却半小时。。。。

算是比较小众吧，僵尸寮需要这个，晚上九点之后寮突没冷却

**Comment by aicezam** [comment]
也对哈，不过这个脚本本质上就是找关键图片，然后点击的过程，只需要截取关键图片，不需要另外开发。。。

**Comment by Color-More** [comment]
了解
