### ISSUE TITLE
桌面版正常模式双开报错

### ISSUE THREAD

**Issue by Zoeyk9** [aicezam/SmartOnmyoji#43]
Error Information:
Type:
Value:list index out of range
Traceback:
兼容模式没问题

**Comment by aicezam** [comment]
第一次用吗？单开没问题么？麻烦截图看下脚本界面的参数设置

**Comment by Zoeyk9** [comment]
单开没问题 ，用了挺久了  一直单开  后来想试试双开 结果不行

![微信截图_20221118213809](https://user-images.githubusercontent.com/118533314/202717852-1af80b1b-0569-49ef-b64f-e9c61a0efb48.png)

**Comment by aicezam** [comment]
可以看下你配置文件吗，这里删了确实也会报错…
![image](https://user-images.githubusercontent.com/39365915/202723438-309b6c00-3c27-4101-ab1d-c26ff3514327.png)

**Comment by aicezam** [comment]
不对啊，我删了也没报错啊，emmmm

**Comment by Zoeyk9** [comment]
[config.txt](https://github.com/aicezam/SmartOnmyoji/files/10041998/config.txt)

**Comment by aicezam** [comment]
找了半天没发现啥问题啊，我电脑也正常运行。。。太奇怪了，你试试把这个值改成False试试，可能是这个原因，我也不能确定

![image](https://user-images.githubusercontent.com/39365915/202728056-af8f0aac-1133-4f96-b8cc-a5c9a480141d.png)

**Comment by aicezam** [comment]
没有复现出来，抱歉 🤣

**Comment by Zoeyk9** [comment]
嗯嗯 感谢大佬

**Comment by Zoeyk9** [comment]
解决了.....我重新安装了一次就ok了
