### ISSUE TITLE
桌面版只能前台运行

### ISSUE THREAD

**Issue by zhouweiu** [aicezam/SmartOnmyoji#44]
桌面版只能前台运行，后台运行一直匹配失败

**Comment by aicezam** [comment]
你勾上调试模式，然后点开始，看看脚本截到的图片呢？

**Comment by zhouweiu** [comment]
> 你勾上调试模式，然后点开始，看看脚本截到的图片呢？

截下来的图不完整
![image](https://user-images.githubusercontent.com/78669122/203227840-f9d46812-eeda-4cc0-8d20-e407bbaff04e.jpg)

**Comment by aicezam** [comment]
是电脑分辨率的问题，你打开脚本的配置文件，改一下“screen-scale-rate”参数，改成1，或者1.25试试，设置里面可以查看电脑实际的分辨率缩放比例，改成一致的就可以了
![image](https://user-images.githubusercontent.com/39365915/203228173-ebcd2b40-ff78-4a65-86d1-20a40bf1f76f.png)

**Comment by zhouweiu** [comment]
那我是1，还有个问题，魂土结算界面不会点击，每次都是等十几秒等到系统自动跳转

**Comment by aicezam** [comment]
那应该是关键图片截图的原因，可以切换为“特征点匹配”，或者重新在魂土结算界面，重新截取一个关键图片，像这样：
![image](https://user-images.githubusercontent.com/39365915/203233042-70f21b49-707e-42bb-9b36-c51d95379196.png)

**Comment by zhouweiu** [comment]
谢谢大佬指点 我试试

**Comment by zhouweiu** [comment]
现在有个问题，可以后台之后，然后我自己也增添了一张截图，可以运行了，但是右边日志显示他一直在匹配用一张图，匹配五次之后停止运行脚本，修改配置文件为false之后又可以了，我想问问一直匹配用一张图片，是正常的吗

**Comment by aicezam** [comment]
啥意思啊，是匹配成功了没有点击到吗？还是说你本身只需要匹配一张图片？如果你只有一张关键图片需要匹配，配置文件改成false就行了，没啥影响，“5次匹配同一个图片就停止脚本”，这个机制是防止界面卡死，一直点同一个位置的情况

**Comment by zhouweiu** [comment]
![B13A9942-22ED-425A-85AE-DE85E9F41EDC](https://user-images.githubusercontent.com/78669122/203313210-e8183885-5118-4a4f-8f5c-1314dc936b77.jpeg)
就像魂土这个，一直匹配“挑战”这个，

**Comment by aicezam** [comment]
是只匹配，没点？

**Comment by zhouweiu** [comment]
运行是正常的，只是右侧日志一直在匹配同一张图

**Comment by a-flying-crow** [comment]
类似的问题，各功能起始位置能匹配但是一直不点

**Comment by aicezam** [comment]
> 类似的问题，各功能起始位置能匹配但是一直不点
可能是分辨率的问题，看看调试模式是不是截全图了吧

**Comment by a-flying-crow** [comment]
> > 类似的问题，各功能起始位置能匹配但是一直不点
> > 可能是分辨率的问题，看看调试模式是不是截全图了吧

应该不是分辨率问题，能匹配但是不点，图是窗口全的

**Comment by aicezam** [comment]
> 应该不是分辨率问题，能匹配但是不点，图是窗口全的

是用的桌面版吗？v0.42 ？如果不是桌面版可能不支持后台点击，要用兼容模式才行。。。。部分电脑环境也会影响点击 😂

**Comment by a-flying-crow** [comment]
> > 应该不是分辨率问题，能匹配但是不点，图是窗口全的
> 
> 是用的桌面版吗？v0.42 ？如果不是桌面版可能不支持后台点击，要用兼容模式才行。。。。部分电脑环境也会影响点击 😂

是桌面版 0.42 各种模式我都尝试过了。 最后这个确实无解。。 就是正常win10 64位

**Comment by aicezam** [comment]
删掉img文件夹里的json文件试试，可能默认的配置在你电脑上点到了其他地方，如果还是不行的话，那我也没辙，除非我能亲眼看到才能找到什么问题，我电脑也是win10 64位，有点搞不懂啥情况 😒
