### ISSUE TITLE
特征点匹配模式问题

### ISSUE THREAD

**Issue by hanwenhao369** [aicezam/SmartOnmyoji#47]
在探索里面使用特征点匹配无法匹配到打完boss结算的那个小宝箱，重新截图试了几次都不行
![reward](https://user-images.githubusercontent.com/60695737/203686474-98d0d798-7f7a-4f08-8b86-b88163dd3d17.jpg)

**Comment by aicezam** [comment]
这。。。应该只有 模板匹配才能匹配到，可能因为图标太小了

**Comment by aicezam** [comment]
是opencv的问题，图片太小的话，生成的特征值就很少，代码可以改，但是大图片的容易识别错，也许可以针对不同尺寸的图片优化一下，以后试试

**Comment by hanwenhao369** [comment]
我现在就是在用模版匹配，但如果刷出来宝箱的话，那个地图会自动移动，就会出现点击错误，点到了27章去，直接gg

**Comment by aicezam** [comment]
自动移动？是因为设置的匹配的间隔太短了？本来要点28章，但是地图还在动，就点到27章了？探索的话，可以把偏移量设置小点试试呢25左右应该差不多，探索的怪本身就在动，不像御魂那么固定

**Comment by hanwenhao369** [comment]
我再去设置设置，多谢作者的回答！
