### ISSUE TITLE
win7截图失败

### ISSUE THREAD

**Issue by dropts** [aicezam/SmartOnmyoji#54]
win7系统下

1. 正常模式 ： 截图不全，右边重点按钮区域都没有

2.兼容模式报错：

初始化中…
第 [ 1 ] 次匹配, 当前进度 [ 0.31% ] 
开始-结束时间 [ 12-04 01:13 --- 12-04 02:13 ]
正在截图…
未知原因导致异常中断，10秒后重试……

**Comment by aicezam** [comment]
最新版吗？最新版应该有一串英文报错的内容，麻烦发一下呢，截图不全是需要改屏幕缩放比例，最新版可以在界面上改，2k显示器一般是1.25或者1.5，比较老的可能是1

**Comment by dropts** [comment]
好的，我刚装完系统可能和运行库有关，我晚上整理好，如果还有问题，我明天给您发上来

**Comment by aicezam** [comment]
我最近换了系统，用的python3.9，打包出来跟win7好像有些功能不兼容会报错，你可以自己用源码编译，或者等改天抽空我折腾一下环境

**Comment by Lin-plax** [comment]
> 我最近换了系统，用的python3.9，打包出来跟win7好像有些功能不兼容会报错，你可以自己用源码编译，或者等改天抽空我折腾一下环境

请问win11兼容吗？最近想升级到win11

**Comment by aicezam** [comment]
> 请问win11兼容吗？最近想升级到win11

脚本兼容，但win11如果在不受支持的硬件设备上安装，会出现其他问题，我就是从win11退回win10的

**Comment by dropts** [comment]
![微信图片_20221204173927](https://user-images.githubusercontent.com/13679700/205483983-3554d728-7268-4815-ab8d-9990b037aa11.png)


昨晚更新最新版，打开即显示如上内容，无法正常启动，太晚了我最终放弃了，因为win7本来就是当时电脑救场临时之举，所以昨晚大半夜更新到win11了，目前使用一切正常，感恩作者。
