### ISSUE TITLE
图片点击定位问题

### ISSUE THREAD

**Issue by Amm0R** [aicezam/SmartOnmyoji#56]
请问一下，这个图片点击是以图片正中心为中点，点击坐标便宜为半径的分布吗？
以探索为例，人手动操作的时候，每次打完小怪后的点击范围其实很大，基本半个屏幕都可能点到。只是重复点击宝箱图案内，其实有点违背平时点击习惯，这是否会被纳入检测范围？
我有一个想法，可以根据图库里的图片大小，让图片里的位置都可以随机点到。这样使用者只需要调整图库里的图片，点击是截图内的位置随机选取。不知道这个想法是不是已经纳入了代码，还是说有更合理的处理方式。

**Comment by aicezam** [comment]
可以看下这个 #45 ，点击的每个点也不是中心点，而是有一定规律，当然也可以给每个图片配置在窗口中的坐标，呈现的最终结果与实际手动的差别不大，愿意折腾的话，也可以按照自己的真实习惯设置json文件来达到更加真实的效果。

**Comment by aicezam** [comment]
另外，你说的问题是0.39版本之前的问题，之后的版本配合使用json文件的偏移坐标，已经不存在了
