### ISSUE TITLE
关于双开魂土结算时概率点击到头像的问题

### ISSUE THREAD

**Issue by saweew** [aicezam/SmartOnmyoji#57]
请问能给双开魂土时结算的头像区域设计一个屏蔽区嘛，如图，双开时如果点到头像或者是聊天就会卡住
![QQ截图20230103121301](https://user-images.githubusercontent.com/121843719/210299390-663a56f7-1b80-4aee-9f9d-6b3699c963a6.png)

**Comment by saweew** [comment]
有时会再次点击到头像框之类的，概率大概十来分钟一次吧，双开的时候

**Comment by aicezam** [comment]
出现这种情况，可以对点击头像框后弹出的信息页面（或弹出的聊天页面），截取一个关键图片，然后在img文件夹下的json配置文件里面，针对这个关键图片，设置一个偏移位置，相当于关闭这个信息页面，这样就能解决你说的卡住的这种情况。

另外，可以查看img文件夹下json配置文件中，关于结算页面的偏移点击位置坐标加减120的范围内，是否包含了这个 ”头像框“ 的位置，如果包含了，可以尝试调整json配置文件中关于这个关键图片的偏移坐标。

至于设计一个屏蔽区这种方案，后面试试能不能自定义到json配置文件里面（对需要匹配的关键图片手动增加一个屏蔽范围，只要计算出的点击坐标在这个区域，就跳过点击）。另外，这种屏蔽方案会有风险，因为在点击热力图中，可能会导致显示 ” 矩形 “ 的空白区域，容易被识别到在开脚本。抽空我研究下具体的情况如果没法避免这种风险，就不会加新功能，还是建议使用第一种方式；

**Comment by saweew** [comment]
好的，谢谢大佬
