### ISSUE TITLE
双开遇到的问题

### ISSUE THREAD

**Issue by gityanbei** [aicezam/SmartOnmyoji#58]
首先感谢作者的脚本！当我使用yuhun文件进行桌面版双开刷魂土时，会遇到当其中一个窗口进入组队界面等待，另一个窗口还在胜利结算界面，此时进行防异常时间等待，因此等待过后错过时间无法组队。经过实践测试，这种情况出现的概率还是比较高的，请问是我的设置没有调整好吗？我可以如何调整解决呢？

**Comment by aicezam** [comment]
是存在这种问题，只能通过把异常等待时间改短一点来解决（10-20秒），这样应该不会错过时间无法组队

**Comment by gityanbei** [comment]
十分感谢，今天更改之后测试成功了
