### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Wkt-MJ** [aicezam/SmartOnmyoji#59]
作者您好，我以前学过python，当然我也很喜欢玩阴阳师，我用pyautogui对于mumu模拟器以外的空间进行操作时可以，但是在作用于模拟器时却无效了是怎么回事？就是可以指示鼠标自动移动至模拟器窗口内，但是却不可以自动点击或者说没有反应。求解实在是想不明白

**Comment by aicezam** [comment]
是不是没有用管理员身份运行？

**Comment by Wkt-MJ** [comment]
mumu模拟器使用管理员身份运行了

**Comment by Wkt-MJ** [comment]
> 是不是没有用管理员身份运行？

实在不行我明天再试试

**Comment by aicezam** [comment]
不是mumu模拟器，是你的代码，要用管理员身份运行

**Comment by Wkt-MJ** [comment]
> 不是mumu模拟器，是你的代码，要用管理员身份运行
没有！我明天试试，真的是谢谢了
