### ISSUE TITLE
使用mumu模拟器需不需要修改图片库？

### ISSUE THREAD

**Issue by xmhcmax** [aicezam/SmartOnmyoji#6]
我自己试了一下好像是不能够识别的，我自己也修改过图片库（结束的那个达摩瓶子始终识别不上），发现它识别了图片但是没有点击效果，有点奇怪。请问大佬，mumu是能正常用吗？

**Comment by aicezam** [comment]
MuMu模拟器不支持后台点击，要用兼容模式哈，后台截图是黑屏的，点击也发送不了点击事件，兼容模式是另一种截图和点击方法，所有窗口都支持

**Comment by aicezam** [comment]
用特征点匹配方法，也不需要重新截图

**Comment by xmhcmax** [comment]
我试了用特征点，开兼容模式，识别不上呜呜呜

**Comment by aicezam** [comment]
不应该啊，有没有截图，调试打开有截图成功吗？

**Comment by aicezam** [comment]
emmm，建议拉最新的代码试试，这两天有更新

**Comment by xmhcmax** [comment]
我用老版本的电脑端试了一下新的（魂土），开
模板匹配：
正常模式匹配上了，显示了点击，没有进入；
兼容模式匹配不上；
特征值匹配：
正常模式匹配上了，显示了点击，没有进入；
兼容模式正常；

**Comment by aicezam** [comment]
emmm，我也不清楚了，我在模拟器、云游戏、手机、电脑版测试都正常的，没出现过这种情况。。。。
另外兼容模式下，游戏窗口不能被遮挡，遮挡才会出现匹配不上的情况，理论上模板匹配用兼容模式也应该正常的；
正常模式不能点击了没生效，说明不兼容游戏窗口（发送点击事件给窗口失败了或者没有正常执行），可能是电脑性能原因，也可能游戏版本太老了，也可能系统原因（没试过在win7上能不能运行），我自己遇到的bug都想办法修复了，你这种情况我着实没办法，可以试试其他大佬写的脚本

**Comment by xmhcmax** [comment]
大佬大佬，我发现正常模式和兼容模式的位置计算有点问题诶
第一张图片是正常模式
![正常模式](https://user-images.githubusercontent.com/102151492/162023787-2bc87c7c-3b23-4ab4-bfc2-5749ac14e71f.jpg)
第二张是兼容模式
![兼容模式](https://user-images.githubusercontent.com/102151492/162023839-39e596fe-d445-453f-be56-deb7f09614e7.jpg)
匹配的是同一张图片，但是位置不一样呢

**Comment by aicezam** [comment]
你是用了特征点匹配方法吗？匹配方法不同计算出来的位置不同是正常的，特征点匹配方法不是很精确，兼容模式下截图方法和后台截图的方法也不一样，截图大小不一样可能计算出的坐标点也不一样，只要能点击都是正常的

另外，建议拉最新的代码，更新了防检测的逻辑，之前的代码可能会收到鬼使黑的来信（之前的脚本默认偏移量太小了，连续一定时间内多次点同一个地方会被判定为作弊）
