### ISSUE TITLE
有安装方法的视频吗，纯小白不懂这个python

### ISSUE THREAD

**Issue by xingxingxing1** [aicezam/SmartOnmyoji#8]

**Comment by aicezam** [comment]
直接下载打包好的程序吧，解压后直接运行 smart_onmyoji_start.exe https://github.com/aicezam/SmartOnmyoji/releases/download/v0.03/smart_onmyoji_start.zip

**Comment by xingxingxing1** [comment]
初始化中…
目标图片读取中……
读取完成！共[ 15 ]张图片
['end_fail.jpg', 'end_win_0.jpg', 'end_win_1.jpg', 'end_win_2.jpg', 'end_win_3.jpg', 'end_win_5.jpg', 'hun11_start.jpg', 'hun11_start1.jpg', 'hun11_start_zhunbei.jpg', 'hun_rukou1.jpg', 'hun_rukou2.jpg', 'hun_rukou3.jpg', 'queren.jpg', 'ready.jpg', 'test.jpg']
第 [ 1 ] 次匹配, 还剩 [ 980 ] 次 
当前进度 [ 0.10% ] 
当前时间 [ 2022-04-27 14:06:36 ]
正在截图…
截图成功！
正在匹配…
匹配失败！
--- [ 5.13 ] 秒后继续，[ 01时29分49秒 ] 后结束---
----------------------------------------------------------
第 [ 2 ] 次匹配, 还剩 [ 979 ] 次 
当前进度 [ 0.20% ] 
当前时间 [ 2022-04-27 14:06:41 ]
正在截图…
截图成功！
正在匹配…
匹配失败！
--- [ 6.07 ] 秒后继续，[ 01时29分43秒 ] 后结束---
----------------------------------------------------------
第 [ 3 ] 次匹配, 还剩 [ 978 ] 次 
当前进度 [ 0.31% ] 
当前时间 [ 2022-04-27 14:06:47 ]
正在截图…
截图成功！
正在匹配…
匹配失败！
--- [ 5.52 ] 秒后继续，[ 01时29分38秒 ] 后结束---
----------------------------------------------------------



老是这样，出现什么问题了吗

**Comment by aicezam** [comment]
你勾一下调试模式，看看正常截屏了没呢，如果显示黑色的截图，说明这个程序窗体不支持后台点击，要用兼容模式才行，目前不支持mumu模拟器，雷电模拟器可以，阴阳师电脑版可以

**Comment by aicezam** [comment]
你勾一下调试模式，看看正常截屏了没呢，如果显示黑色的截图，说明这个程序窗体不支持后台点击，要用兼容模式才行，目前不支持mumu模拟器，雷电模拟器可以，阴阳师电脑版可以

**Comment by xingxingxing1** [comment]
试了一下，黑色图片。我用的是阴阳师电脑版，然后用v5多开器多开一个，想双开挖土的，兼容模式我也用了，之后还用了特征点，一样不行，咋搞

**Comment by aicezam** [comment]
好像不支持多开，俩程序名称一样，在找窗口的时候，会有冲突，回头我加个兼容多开的功能吧~

**Comment by xingxingxing1** [comment]
现在有空加吗，太期待了！

**Comment by xingxingxing1** [comment]
单开我也试了，还是黑色图片，还是匹配失败，好烦啊

**Comment by xingxingxing1** [comment]
单开我也试了，还是黑色图片，还是匹配失败，好烦啊

**Comment by aicezam** [comment]
这。。。。。你试试其他软件呢？先用“选择窗体”获取名称（脚本里面填的那个窗口名字一定要跟游戏的窗口名字一样），再勾上调试模式，再开始，看看是不是有截图成功，如果还是没有，可能不兼容你的系统啥的，无能为力了就。。。如果能截图成功，就能正常使用

**Comment by xingxingxing1** [comment]
初始化中…
目标图片读取中……
读取完成！共[ 15 ]张图片
['end_fail.jpg', 'end_win_0.jpg', 'end_win_1.jpg', 'end_win_2.jpg', 'end_win_3.jpg', 'end_win_5.jpg', 'hun11_start.jpg', 'hun11_start1.jpg', 'hun11_start_zhunbei.jpg', 'hun_rukou1.jpg', 'hun_rukou2.jpg', 'hun_rukou3.jpg', 'queren.jpg', 'ready.jpg', 'test.jpg']
第 [ 1 ] 次匹配, 还剩 [ 980 ] 次 
当前进度 [ 0.10% ] 
当前时间 [ 2022-04-28 16:02:55 ]
正在截图…
截图成功！
正在匹配…
 第 [ 1 ] 张图片，匹配分数：[ 0.26 ]
 第 [ 2 ] 张图片，匹配分数：[ 0.59 ]
 第 [ 3 ] 张图片，匹配分数：[ 0.26 ]
 第 [ 4 ] 张图片，匹配分数：[ 0.55 ]
 第 [ 5 ] 张图片，匹配分数：[ 0.66 ]
 第 [ 6 ] 张图片，匹配分数：[ 0.76 ]
 第 [ 7 ] 张图片，匹配分数：[ 0.39 ]
 第 [ 8 ] 张图片，匹配分数：[ 0.51 ]
 第 [ 9 ] 张图片，匹配分数：[ 0.24 ]
 第 [ 10 ] 张图片，匹配分数：[ 0.53 ]
 第 [ 11 ] 张图片，匹配分数：[ 0.47 ]
 第 [ 12 ] 张图片，匹配分数：[ 0.38 ]
 第 [ 13 ] 张图片，匹配分数：[ 0.28 ]
 第 [ 14 ] 张图片，匹配分数：[ 0.48 ]
 第 [ 15 ] 张图片，匹配分数：[ 0.39 ]
匹配失败！
--- [ 5.66 ] 秒后继续，[ 01时29分49秒 ] 后结束---
------------------------------------------


然后当我把阴阳师电脑版最小化时，它是这样的，是哪出问题了吗
初始化中…
目标图片读取中……
读取完成！共[ 15 ]张图片
['end_fail.jpg', 'end_win_0.jpg', 'end_win_1.jpg', 'end_win_2.jpg', 'end_win_3.jpg', 'end_win_5.jpg', 'hun11_start.jpg', 'hun11_start1.jpg', 'hun11_start_zhunbei.jpg', 'hun_rukou1.jpg', 'hun_rukou2.jpg', 'hun_rukou3.jpg', 'queren.jpg', 'ready.jpg', 'test.jpg']
第 [ 1 ] 次匹配, 还剩 [ 980 ] 次 
当前进度 [ 0.10% ] 
当前时间 [ 2022-04-28 16:05:03 ]
正在截图…
截图成功！
正在匹配…
Error Information:
Type: <class 'cv2.error'>
Value: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

Traceback: <traceback object at 0x000001F8437E0248>

**Comment by xingxingxing1** [comment]
而且开启调式模式后，截图给我的是两张黑色的，除了大小不一样，其他都是一样的，可我是单开啊

**Comment by aicezam** [comment]
游戏窗口最小化之后，不能截图哈，至于出现2张截图，是因为其中一张是原图，另一张是压缩后的，**兼容模式下窗口置顶不能被遮挡，麻烦再试试呢**，除了阴阳师也试试别的能否正常截图呢，比如浏览器、电脑资源管理器之类的试试~

**Comment by xingxingxing1** [comment]
浏览器我试了一下，截图是一片黑，我也不知道为啥会这样

**Comment by xingxingxing1** [comment]
我又试了一下网易云音乐，截图是网易云正常的界面，然后颜色依旧是黑白

**Comment by aicezam** [comment]
颜色黑白是正常的，我做了转灰度处理，能截图说明没问题呀，可以贴一张你截图的那个阴阳师的那个黑色图片不？还有参数设置的界面

**Comment by xingxingxing1** [comment]
![scr_img](https://user-images.githubusercontent.com/90946244/165742344-c354b84d-7f66-4e0c-b377-eaf3f7618f40.png)
![微信图片_20220428192611](https://user-images.githubusercontent.com/90946244/165742359-72e2f2b2-55e4-4f3a-b976-571a09ba288e.png)

**Comment by xingxingxing1** [comment]
![Uploading 微信图片_20220428192831.png…]()

**Comment by xingxingxing1** [comment]
![Uploading 微信图片_20220428192831.png…]()

**Comment by xingxingxing1** [comment]
![Uploading 微信图片_20220428193024.png…]()

**Comment by xingxingxing1** [comment]
![Uploading jietu.png…]()

**Comment by aicezam** [comment]
。。。。。。我知道啥原因了，都用默认参数吧，可能你游戏窗口的分辨率比较大，所以匹配失败，可以尝试一下：
1. 把压缩截图那个拉到最右边，意思是不压缩
2. 你打开游戏后，不调整分辨率，先把要点击的位置的截图重新截图放到程序的img文件夹下面，替换自带的截图，之前的截图是我电脑的分辨率的，跟你电脑可能不一样

**Comment by xingxingxing1** [comment]
img文件夹里面没有这个scr-img截图呀，咋替换

**Comment by aicezam** [comment]
img文件夹下面不是有御魂 探索 百鬼这些文件夹嘛，文件夹里面有很多图片，你把这些图片挨个替换成你自己的重新搞的截图

**Comment by xingxingxing1** [comment]
![微信图片_20220428202219](https://user-images.githubusercontent.com/90946244/165751096-e7484a07-dae5-4be1-b0ab-f1bdd7a36d31.png)
![微信图片_20220428202223](https://user-images.githubusercontent.com/90946244/165751110-310117b2-9772-44fc-9b67-d1bf2c2d2ec6.png)

**Comment by aicezam** [comment]
图片格式用jpg哈，png识别不到

**Comment by xingxingxing1** [comment]
我看了一下你img里的图片，这明明就是单开的挖土，一般挖土都是两个人一起，然后目标图片读取能不能改一下

**Comment by aicezam** [comment]
多开的话可以多截两张图，那个自动邀请勾上一样的，读取格式后面有空就改下

**Comment by xingxingxing1** [comment]
![微信图片_20220428203119](https://user-images.githubusercontent.com/90946244/165752558-8ddfb1cc-e2bf-4dd7-a21c-0c05408355cd.png)
![微信图片_20220428203153](https://user-images.githubusercontent.com/90946244/165752569-599bcf44-aa29-4e70-b353-8db6a5c77952.png)

**Comment by xingxingxing1** [comment]
还是不行，怎么弄

**Comment by aicezam** [comment]
emmmmm，没辙了，我觉得还是截图分辨率的问题，具体怎么弄我看不到你电脑，我也搞不定了，对了，你电脑是不是设置了分辨率缩放，这个改成100%再截图试试，可能因为实际显示分辨率比较大，但是截图因为有缩放，所以截图实际大小跟你电脑游戏分辨率不一致。。。。。大概，可能这个原因
![image](https://user-images.githubusercontent.com/39365915/165758037-719cb947-50a4-470e-abf2-e189b75d9e42.png)

**Comment by xingxingxing1** [comment]
改了100%，有用，但不支持双开，希望早点优化一下

**Comment by aicezam** [comment]
已更新支持多开方法，需要开启多个脚本，每个脚本对应一个窗口，且需要勾选“双开”并点击“选择窗体”

**Comment by xingxingxing1** [comment]
今早我试了一下，可以，但跟那个100%，125%没关系，是img里面的图片的问题，我把你里面的图片全部换成我自己截图的图片，大概率可以点击到，然后匹配成功概率特高，不过有个小建议，就是能不能一个脚本控制两个阴阳师电脑版

**Comment by aicezam** [comment]
可以，但没时间，抽空可以优化一下

**Comment by xingxingxing1** [comment]
![微信图片_20220429131626](https://user-images.githubusercontent.com/90946244/165889041-36cd0716-8098-41f4-b1d3-43dd6859f0ec.png)

**Comment by xingxingxing1** [comment]
又出现问题了，双开脚本只能一个脚本有用

**Comment by aicezam** [comment]
> 又出现问题了，双开脚本只能一个脚本有用

你用正常模式吧，桌面版支持后台点击，看报错信息是兼容模式里面的窗口置顶方法有问题

**Comment by xingxingxing1** [comment]
司机的脚本只能兼容模式，打手的脚本只能正常模式，匹配方法都是特征点，模板匹配不行

**Comment by aicezam** [comment]
你这情况也太奇怪了，讲道理不应该这样啊，匹配不到可能还是截图的问题，但是俩窗口按理应该都能正常模式运行的，不过现在能用就行，五一我看看能不能优化一下

**Comment by xingxingxing1** [comment]
有点期待，到时候有更新了记得回复我，我第一时间就去试试你的新作品

**Comment by aicezam** [comment]
已更新代码，https://github.com/aicezam/SmartOnmyoji/releases

**Comment by aicezam** [comment]
另外，可以顺便点个star么~ @xingxingxing1

**Comment by xingxingxing1** [comment]
试了一下，我的电脑只能用兼容模式加特征点方案，正常模式下不管哪个匹配方法都不行，一个脚本支持两个阴阳师电脑版，这个优化特好，支持，星星俺点了，期待下一次优化

**Comment by xingxingxing1** [comment]
![微信图片_20220430074149](https://user-images.githubusercontent.com/90946244/166081267-07134810-d7b6-4dc5-80b0-3f5d02df6fff.png)

**Comment by xingxingxing1** [comment]
正常模式下，用特征点匹配方法，能截图成功，然后就是鼠标不会点击挑战，这个就很迷

**Comment by aicezam** [comment]
> 试了一下，我的电脑只能用兼容模式加特征点方案，正常模式下不管哪个匹配方法都不行，一个脚本支持两个阴阳师电脑版，这个优化特好，支持，星星俺点了，期待下一次优化

只能用特征点方法，说明是图片大小和分辨率的问题，可以把那个压缩截图那个条拖到最右边，就是不压缩的意思，可能有用~代码上没法再优化了

**Comment by xingxingxing1** [comment]
试了一下压缩截图右边拉满，一样没反应。电脑暂且用兼容模式加特征点挖土，能用就行，嘿嘿

**Comment by xingxingxing1** [comment]
它这个探索，怎么老是失败，不管双开还是单开，运行模式和匹配方法都换了四种，没有一种是阴阳师里面自己会动的，停在界面一动不动，大佬你自己试过这个探索模板吗，是我这边不兼容还是什么问题...

**Comment by aicezam** [comment]
我这边一切正常（看图），探索的原理：是按照模板图片的顺序，先找怪物头上的那个图标，找不到会去点地图其他地方，另外，探索文件夹里的截图，只适用困难28
![1](https://user-images.githubusercontent.com/39365915/189508591-9e371105-9ccb-4d4a-abb0-d0c27c22e593.gif)

**Comment by aicezam** [comment]
1、建议开启调试，看看截图，是否能成功匹配：开启调试后，一次匹配会显示2张图片，第一张是脚本对窗口截图，关闭后会显示第二张截图，第二张是在第一张截图的基础上画圈，表示匹配到的位置。如果日志里面显示的匹配分数太小，说明可能是模板截图或者分辨率的问题，重新截图或者调整下分辨率应该就没问题了
2、由于分辨率的问题，可能会导致匹配不上，你可以试试按照最新版的方法，设置一下脚本配置参数中分辨率的值
![QQ截图20220911094923](https://user-images.githubusercontent.com/39365915/189508644-1a0505de-7475-4343-963a-e19ab1db0e44.jpg)
![QQ图片20220911095010](https://user-images.githubusercontent.com/39365915/189508647-a8a3f8ea-59bd-4003-bdae-d717d184bb08.png)
